spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: xxx
    port: 6379

# 自定义想线程池
gulishop:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300
