spring:
  cloud:
    nacos:
      discovery:
        access-addr: 127.0.0.1:8848
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
    thymeleaf:
      cache: false
    alicloud:
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
  # 注册验证码校验
  redis:
    port: 6379
    host: xxx




